# Generated by Django 4.2.22 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de materia')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la materia')),
                ('nrc', models.CharField(max_length=10, verbose_name='NRC')),
                ('carreras_permitidas', models.JSONField(default=list, verbose_name='Carreras que pueden cursar esta materia')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'materias',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='carrera',
            field=models.CharField(blank=True, choices=[('ICC', 'Ingeniería en Cs. de la Computación'), ('LCC', 'Licenciatura en Cs. de la Computación'), ('ITI', 'Ingeniería en Tecnologías de la Información')], max_length=10, verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='user',
            name='materias_docente',
            field=models.ManyToManyField(blank=True, related_name='docentes', to='users.materia', verbose_name='Materias que imparte el docente'),
        ),
        migrations.AddField(
            model_name='user',
            name='materias_estudiante',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', to='users.materia', verbose_name='Materias del estudiante'),
        ),
    ]
