# Generated by Django 4.2.22 on 2026-02-07 00:00

from django.db import migrations


def populate_materias(apps, schema_editor):
    """
    Popular la tabla de materias con las 5 materias disponibles
    """
    Materia = apps.get_model('users', 'Materia')
    
    materias_base = [
        {
            'codigo': 'MDW_49067',
            'nombre': 'Modelos de Desarrollo Web',
            'nrc': '49067',
            'carreras_permitidas': ['ITI']
        },
        {
            'codigo': 'SO1_50153',
            'nombre': 'Sistemas Operativos I',
            'nrc': '50153',
            'carreras_permitidas': ['LCC', 'ICC']
        },
        {
            'codigo': 'SO2_50165',
            'nombre': 'Sistemas Operativos II',
            'nrc': '50165',
            'carreras_permitidas': ['LCC', 'ICC']
        },
        {
            'codigo': 'IS_48189',
            'nombre': 'Ingeniería de Software',
            'nrc': '48189',
            'carreras_permitidas': ['LCC', 'ICC']
        },
    ]
    
    for materia_data in materias_base:
        Materia.objects.create(**materia_data)


def reverse_populate_materias(apps, schema_editor):
    """
    Revertir la población de materias (eliminarlas)
    """
    Materia = apps.get_model('users', 'Materia')
    Materia.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_materia_alter_user_carrera_user_materias_docente_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_materias, reverse_populate_materias),
    ]
