# Generated by Django 4.2.22 on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_populate_materias'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254, verbose_name='Correo destinatario')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto del email')),
                ('tipo', models.CharField(choices=[('recovery_code', 'Código de Recuperación'), ('task_assigned', 'Tarea Asignada'), ('submission_received', 'Entrega Recibida'), ('task_graded', 'Tarea Calificada'), ('task_reminder', 'Recordatorio de Tarea'), ('welcome', 'Bienvenida')], max_length=50, verbose_name='Tipo de email')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido')], default='enviado', max_length=20, verbose_name='Estado del envío')),
                ('mensaje_error', models.TextField(blank=True, null=True, verbose_name='Mensaje de error (si falló)')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de envío')),
                ('brevo_message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del mensaje en Brevo')),
            ],
            options={
                'verbose_name': 'Registro de Email',
                'verbose_name_plural': 'Registros de Emails',
                'db_table': 'email_logs',
                'ordering': ['-fecha_envio'],
                'indexes': [
                    models.Index(fields=['-fecha_envio'], name='email_logs_fecha_e_idx'),
                    models.Index(fields=['destinatario'], name='email_logs_destina_idx'),
                    models.Index(fields=['tipo'], name='email_logs_tipo_idx'),
                    models.Index(fields=['estado'], name='email_logs_estado_idx'),
                ],
            },
        ),
    ]
